### ISSUE TITLE
npm installed comunica-web-client-generator throws 'error: Detected fatal error.'

### ISSUE THREAD

**Issue by phivk** [comunica/jQuery-Widget.js#99]
I just installed via `npm install -g @comunica/web-client-generator` and ran
```
$ comunica-web-client-generator
```

First this logs a long list of warnings originating from `Components.js` in the form:
```
[Components.js] warn: Detected remote context lookup for 'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/runner/^1.0.0/components/context.jsonld' in /Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/config/config-default.json. This may indicate a missing or invalid dependency, or an invalid context URL.
```

followed by the following error:
```
[Components.js] error: Detected fatal error. Generated 'componentsjs-error-state.json' with more information.
ErrorResourcesContext: Could not find (valid) component types for config "urn:comunica:my" among its types, or a requireName
configTypes: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/runner/Runner
config: {
  term: NamedNode { termType: 'NamedNode', value: 'urn:comunica:my' },
  properties: {
    'http://www.w3.org/2000/01/rdf-schema#seeAlso': [
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource],
      [Resource], [Resource]
    ],
    'http://www.w3.org/1999/02/22-rdf-syntax-ns#type': [ [Resource] ],
    'https://linkedsoftwaredependencies.org/bundles/npm/@comunica/runner/actor': [
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource],
      [Resource], [Resource], [Resource], [Resource], [Resource]
    ],
    'http://usefulinc.com/ns/doap#name': []
  }
}
    at ConfigPreprocessorComponentMapped.canHandle (/Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/node_modules/componentsjs/lib/preprocess/ConfigPreprocessorComponent.js:37:23)
    at ConfigPreprocessorComponentMapped.canHandle (/Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/node_modules/componentsjs/lib/preprocess/ConfigPreprocessorComponentMapped.js:28:38)
    at ConfigConstructorPool.getRawConfig (/Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/node_modules/componentsjs/lib/construction/ConfigConstructorPool.js:68:53)
    at ConfigConstructorPool.instantiate (/Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/node_modules/componentsjs/lib/construction/ConfigConstructorPool.js:46:34)
    at ComponentsManager.instantiate (/Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/node_modules/componentsjs/lib/ComponentsManager.js:42:54)
    at compileConfig (/Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/node_modules/componentsjs/lib/util/CompileUtil.js:27:53)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/phivk/.nvm/versions/node/v12.20.0/lib/node_modules/@comunica/web-client-generator/bin/generate.js:37:5
```

system setup:
- Node version v12.20.0
- macOS 10.15.7

Any help would be appreciated :)

**Comment by rubensworks** [comment]
Thanks for reporting, fixed in 1.3.2.
